
spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:/Users/kąkuter/IdeaProjects/TaskSpringApp3/todo-db'
  jpa:
    hibernate:
      ddl-auto: update







